import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.wk'
version = '0.0.1-SNAPSHOT'
description = 'ti-orchestrator-api'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'

    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // Metrics
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'

    // Micrometer Tracing -> OpenTelemetry
    runtimeOnly 'io.micrometer:micrometer-tracing-bridge-otel'

    // Spring Boot OpenTelemetry tracing auto-configuration
    implementation 'org.springframework.boot:spring-boot-micrometer-tracing-opentelemetry'

    // Spring Boot Zipkin support
    implementation 'org.springframework.boot:spring-boot-zipkin'

    // OpenTelemetry -> Zipkin exporter
    runtimeOnly 'io.opentelemetry:opentelemetry-exporter-zipkin'
    // Context Propagation for Web Clients / Feign / RestTemplate
    implementation 'io.micrometer:micrometer-observation'

    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'org.springframework.amqp:spring-rabbit-stream'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-actuator-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-amqp-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-zipkin-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.testcontainers:testcontainers-rabbitmq'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.processResources {
    filesMatching('application.yaml') {
        filter(ReplaceTokens, tokens: [
                'project.version': project.version.toString()
        ])
    }
}

tasks.named('jar') {
    enabled = false
}